SUN = 0
MOON = 1
MERCURY = 2
VENUS = 3
MARS = 4
JUPITER = 5
SATURN = 6
URANUS = 7
NEPTUNE = 8
PLUTO = 9
MEAN_NODE = 10
TRUE_NODE = 11
MEAN_APOGEE = 12
OSC_APOGEE = 13
EARTH = 14
CHIRON = 15
PHOLUS = 16
CERES = 17
PALLAS = 18
JUNO = 19
VESTA = 20
INTP_APOGEE = 21
INTP_PERIGEE = 22
ASC = 23
MC = 24
DSC = 25
IC = 26
DAY_PARS = 27
NIGHT_PARS = 28
SOUTH_NODE = 29
MARRIAGE_PARS = 30
BLACK_SUN = 31
VULCANUS = 32
PERSEPHONE = 33
TRUE_LILITH = 34

PLANETS = [
    'SUN', 'MOON', 'MERCURY', 'VENUS', 'MARS', 'JUPITER', 'SATURN',
    'URANUS', 'NEPTUNE', 'PLUTO', 'MEAN NODE', 'TRUE NODE', 'MEAN APOGEE', 'OSC. APOGEE',
    'EARTH', 'CHIRON', 'PHOLUS', 'CERES', 'PALLAS', 'JUNO', 'VESTA',
    'INTP. APOGEE', 'INTP. PERIGEE', 'ASC', 'MC', 'DSC', 'IC', 'DAY PARS',
    'NIGHT PARS', 'SOUTH NODE', 'MARRIAGE PARS', 'BLACK SUN', 'VULCANUS', 'PERSEPHONE',
    'TRUE LILITH']

ASPECT_DEGREE = [0, 30, 45, 60, 72, 90, 120, 135, 144, 150, 180]
ASPECT_NAME = ['conjunction', 'semisextile', 'semisquare', 'sextile', 'quintile', 'square', 'trine', 'sesquiquadrate',
               'biquintile', 'quincunx', 'opposition']

CONJUNCTION = 0
SEMISEXTILE = 1
SEMISQUARE = 2
SEXTILE = 3
QUINTILE = 4
SQUARE = 5
TRINE = 6
SESQUIQUADRATE = 7
BIQUINTILE = 8
QUINCUNX = 9
OPPOSITION = 10
